// <auto-generated />
using ForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Data.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    [Migration("20230603124739_CreatedTables")]
    partial class CreatedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Praesent rhoncus luctus ante. Quisque in dolor ut odio efficitur vehicula vel a turpis. Cras ut magna mi. Nam ante.",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Aliquam erat volutpat. Vestibulum luctus lacus nec diam aliquam egestas. Morbi neque arcu, pharetra eget mi a, lobortis condimentum risus.",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Nunc sagittis fringilla orci, nec pharetra dolor faucibus a. Nunc vehicula arcu non purus consectetur sagittis. Nunc volutpat tincidunt nisl.",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
